export const defaultPolicies = [
  {
    category: 'Travel',
    limit: 5000,
    currency: 'INR',
    receiptRequired: true,
    requiresBusinessPurpose: false,
    requiresClientInfo: false,
    policyText: 'Travel expenses including flights, trains, taxis, and fuel are reimbursable up to ₹5,000 per trip. Original receipts or tickets must be submitted. Travel should be pre-approved for amounts exceeding ₹3,000.',
    notes: 'Includes local commute for business purposes.',
  },
  {
    category: 'Meals',
    limit: 2000,
    currency: 'INR',
    receiptRequired: true,
    requiresBusinessPurpose: false,
    requiresClientInfo: false,
    policyText: 'Meal expenses are reimbursable up to ₹2,000 per day. Receipts are required for all claims. Alcohol is not reimbursable under this category.',
    notes: 'Per-day limit applies. Team meals require attendee list.',
  },
  {
    category: 'Accommodation',
    limit: 7500,
    currency: 'INR',
    receiptRequired: true,
    requiresBusinessPurpose: false,
    requiresClientInfo: false,
    policyText: 'Accommodation expenses are reimbursable up to ₹7,500 per night. Hotel bills or receipts must be submitted. Booking should be made through approved corporate channels when possible.',
    notes: 'For outstation business trips only.',
  },
  {
    category: 'Client Entertainment',
    limit: 5000,
    currency: 'INR',
    receiptRequired: true,
    requiresBusinessPurpose: true,
    requiresClientInfo: true,
    policyText: 'Client entertainment expenses are reimbursable up to ₹5,000 when the business purpose and client information are documented. Receipts are mandatory. Pre-approval is required for amounts above ₹3,000.',
    notes: 'Must include client name and business purpose in description.',
  },
  {
    category: 'Office Supplies',
    limit: 3000,
    currency: 'INR',
    receiptRequired: true,
    requiresBusinessPurpose: false,
    requiresClientInfo: false,
    policyText: 'Office supply expenses are reimbursable up to ₹3,000 per month. Receipts are required. Items must be for direct business use. Personal items are not reimbursable.',
    notes: 'Consumables only. Equipment purchases require separate approval.',
  },
  {
    category: 'Communication',
    limit: 1500,
    currency: 'INR',
    receiptRequired: false,
    requiresBusinessPurpose: false,
    requiresClientInfo: false,
    policyText: 'Communication expenses including phone bills and internet for business use are reimbursable up to ₹1,500 per month. Receipts are preferred but not mandatory for amounts under ₹500.',
    notes: 'Mobile and internet bills for remote work are covered.',
  },
  {
    category: 'Other',
    limit: 2000,
    currency: 'INR',
    receiptRequired: true,
    requiresBusinessPurpose: true,
    requiresClientInfo: false,
    policyText: 'Miscellaneous business expenses not covered by other categories are reimbursable up to ₹2,000 with prior approval. The business purpose must be clearly documented.',
    notes: 'Requires manager approval before submission.',
  },
]
